#!/bin/sh

if [ $(ps aux | grep $USER | grep node | grep -v grep | wc -l | tr -s "\n") -eq 0 ]
then
        export NODE_ENV=prod
        export PORT=80
		
		echo "$(date) Forever not running, will try to start the app."
        /usr/bin/node /usr/local/bin/forever start /root/sws/server.js
        
else
	echo "$(date) Node or Forever is running, no need to start."
fi
